on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Coverage

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Coverage

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2.9.0

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
          needs: check

      - name: Running coverage
        run: |
          # Files to exclude
          # files <- list.files("inst/", full.names = TRUE, recursive = TRUE)

          # Run coverage
          covr::codecov(
            line_exclusions = as.list(files),
            token = Sys.getenv("CODECOV_TOKEN")
            )
        shell: Rscript {0}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
